// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// simulateCRN
int simulateCRN(Rcpp::IntegerMatrix stoichMatrix, Rcpp::IntegerMatrix reactantMatrix, Rcpp::List config, String outFileSC, String outFileParams, String outFileIC, String outFileConverge, const int stepper);
RcppExport SEXP _racipeCRN_simulateCRN(SEXP stoichMatrixSEXP, SEXP reactantMatrixSEXP, SEXP configSEXP, SEXP outFileSCSEXP, SEXP outFileParamsSEXP, SEXP outFileICSEXP, SEXP outFileConvergeSEXP, SEXP stepperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type stoichMatrix(stoichMatrixSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type reactantMatrix(reactantMatrixSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type config(configSEXP);
    Rcpp::traits::input_parameter< String >::type outFileSC(outFileSCSEXP);
    Rcpp::traits::input_parameter< String >::type outFileParams(outFileParamsSEXP);
    Rcpp::traits::input_parameter< String >::type outFileIC(outFileICSEXP);
    Rcpp::traits::input_parameter< String >::type outFileConverge(outFileConvergeSEXP);
    Rcpp::traits::input_parameter< const int >::type stepper(stepperSEXP);
    rcpp_result_gen = Rcpp::wrap(simulateCRN(stoichMatrix, reactantMatrix, config, outFileSC, outFileParams, outFileIC, outFileConverge, stepper));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_racipeCRN_simulateCRN", (DL_FUNC) &_racipeCRN_simulateCRN, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_racipeCRN(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
