# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulateCRN <- function(stoichMatrix, reactantMatrix, config, outFileSC, outFileParams, outFileIC, outFileConverge, stepper = 1L) {
    .Call(`_racipeCRN_simulateCRN`, stoichMatrix, reactantMatrix, config, outFileSC, outFileParams, outFileIC, outFileConverge, stepper)
}

